import { CONFIG_AUTH_ENDPOINT, CONFIG_SEAT_ENDPOINT } from "../config";

export const API_ENDPOINTS = {
  REGISTER: `${CONFIG_AUTH_ENDPOINT}/register`,
  LOGIN: `${CONFIG_AUTH_ENDPOINT}/login`,
  // GOOGLE_SIGN_IN: `${CONFIG_ENDPOINT}/google-login`,
  PROTECTED:`${CONFIG_AUTH_ENDPOINT}/protected`,
  SEAT_BOOK:`${CONFIG_SEAT_ENDPOINT}/seatBook`,
  BOOKED_SEAT_RESET: `${CONFIG_SEAT_ENDPOINT}/bookedSeatReset`
};


